### ISSUE TITLE
std::cin maybe breaking c plus plus code

### ISSUE THREAD

**Issue by ejyager00** [s-gannon/cpp-uttt#1]
@ehawkvu Can you help with this?
@s-gannon Can you better explain this issue?

**Comment by s-gannon** [comment]
After all the input is received, none of the conditionals starting from line 127 seem to run. The code seems to skip right over the conditionals despite having an else statement and skips right to the final print and return 0 statement. There might be a problem with the recursive call? I receive no errors or warnings when running or compiling the program (this is without the OpenMP stuff currently)

**Comment by echawk** [comment]
I'm pretty sure that it is the comparasions that are in both `ttt.cpp` and `uttt.cpp`. In many of the if statements, the pattern of
`a == b == 2` is common, however it is not doing the proper comparasion, instead comparing the result of the expression `a == b` with `2` which will always be false.

It also fails to compile with the makefile because `uttt.cpp` has an undefined reference to 'board'.

**Comment by s-gannon** [comment]
Implemented all fixes that the -pedantic flag threw at me and fixed all things above. Closing this issue, but if you find something else feel free to create another
